# docker-compose.yaml

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    ports:
      - "3000:8080"
    networks:
      - openwebui-shared
    volumes:
      - ./data/openwebui:/app/backend/data
      - ./config:/app/config  
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true            # remove old images
      - WATCHTOWER_POLL_INTERVAL=3600      # check every hour
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_KEEP_ALIVE=315360000  # 10 years in seconds
    volumes:
      - ./data/ollama:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 5s
      timeout: 3s
      retries: 3

  tailscale:
    build:
      context: .
      dockerfile: dockerfile.tailscale
    container_name: tailscale
    hostname: openwebui
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./data/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

networks:
  openwebui-shared:
    external: true
