"""egress-allowlist — the worker git-egress scope, remotely managed via Mattermost.

Workers reach git ONLY through the `ao-git-egress` tinyproxy, which permits ONLY hosts in its
filter file (default-deny; the blast-radius boundary, governance §5). To let the org work on ANY
project the operator onboards — without a container rebuild — the bridge OWNS that filter file:
it renders `seed ∪ project-hosts ∪ manually-allowed − suppressed` to the mounted allowlist path,
and the egress proxy reloads on change (SIGHUP via a file-watch wrapper). So `/project add` (or
`/egress allow`) from chat widens the scope; the change is auditable and operator-driven.

The bridge writing the file is the remote-change mechanism; making it take effect live is the
egress container's reload wrapper (compose). If no path is configured (dev/tests), rendering still
works — only the file write is skipped.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

from sqlalchemy import select

from ..db import Database
from ..models import EgressHost
from .audit_sink import AuditSink
from .projects import ProjectRegistry, host_of

log = logging.getLogger("agent_bridge.egress")

# Always-allowed baseline (matches the little-coder seed) so GitHub works out of the box.
_SEED_HOSTS = ["github.com", "githubusercontent.com"]


def _pattern(host: str) -> str:
    """tinyproxy extended-regex matching the host and any subdomain (case-insensitive upstream)."""
    return rf"^(.*\.)?{re.escape(host)}$"


class EgressAllowlist:
    def __init__(
        self, db: Database, audit: AuditSink, projects: ProjectRegistry, path: str = ""
    ) -> None:
        self.db = db
        self.audit = audit
        self.projects = projects
        self.path = path

    async def allow(self, host: str, *, added_by: str = "operator", source: str = "manual") -> str:
        """Allow a host (or re-activate a suppressed one). Accepts a bare host or a full repo URL."""
        h = (host_of(host) or host).strip().lower()
        if not h:
            raise ValueError("empty host")
        async with self.db.session_factory() as s:
            row = await s.get(EgressHost, h)
            if row is None:
                s.add(EgressHost(host=h, added_by=added_by, source=source, active=True))
            else:
                row.active = True
                row.added_by = added_by
            await s.commit()
        await self.audit.log("egress_host_allowed", actor=added_by, payload={"host": h})
        return h

    async def remove(self, host: str, *, actor: str = "operator") -> str:
        """Suppress a host (an inactive row overrides seed/project inclusion)."""
        h = (host_of(host) or host).strip().lower()
        async with self.db.session_factory() as s:
            row = await s.get(EgressHost, h)
            if row is None:
                s.add(EgressHost(host=h, added_by=actor, source="manual", active=False))
            else:
                row.active = False
            await s.commit()
        await self.audit.log("egress_host_removed", actor=actor, payload={"host": h})
        return h

    async def hosts(self) -> list[str]:
        """Effective allowlist = seed ∪ project hosts ∪ active manual − suppressed."""
        base: set[str] = set(_SEED_HOSTS) | await self.projects.hosts()
        async with self.db.session_factory() as s:
            rows = (await s.execute(select(EgressHost))).scalars().all()
        for r in rows:
            if r.active:
                base.add(r.host)
            else:
                base.discard(r.host)
        return sorted(base)

    async def render(self) -> str:
        hosts = await self.hosts()
        lines = [
            "# agent-org egress allowlist — GENERATED by agent-bridge (do not hand-edit).",
            "# Manage via `/project add` or `/egress allow|remove` in Mattermost.",
            "# tinyproxy extended-regex, one host pattern per line (default-deny).",
            "",
        ]
        lines += [_pattern(h) for h in hosts]
        return "\n".join(lines) + "\n"

    async def sync(self) -> str:
        """Render + write the allowlist file (best-effort). Returns the rendered content."""
        content = await self.render()
        if self.path:
            try:
                p = Path(self.path)
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(content, encoding="utf-8")
                log.info("egress allowlist written to %s (%d hosts)", self.path, content.count("^"))
            except Exception as exc:  # noqa: BLE001 - never block onboarding on a write hiccup
                log.warning("could not write egress allowlist %s: %s", self.path, exc)
        return content

    async def is_allowed(self, host_or_url: str) -> bool:
        h = (host_of(host_or_url) or host_or_url).strip().lower()
        return h in set(await self.hosts())
