"""DIFFERENTIAL over one corpus: the daemon's real loader vs the gate's
commit-time decider.

The defect this replaces: `check-judge-flag.ps1` decided "is the flag being
turned on?" with a regex over staged text while the daemon decided it with
`yaml.safe_load` + pydantic. Two parsers, two answers. A verifier turned the
flag on for the daemon with three ordinary YAML spellings and walked past the
grep; a second did it with two quote characters.

The fix is that there is now ONE parser (`judge_gate.enabled_in_yaml_text`
calls the same `yaml.safe_load` the daemon calls, and coerces with the
daemon's OWN pydantic annotation). This file is the executable proof that the
two answers cannot drift apart again, over a corpus generated by mechanism --
scalar case, scalar quoting, key quoting and hex escaping, flow style, anchor
and alias, merge key, document structure, whitespace, comments, relocation --
rather than collected from what a verifier happened to try.

The corpus file is shared with `scripts/checks/verify-judge-flag-guard.ps1`,
which drives the SHIPPED pre-commit guard over the same rows end to end in a
scratch git repository. One corpus, two executors: the house pattern of two
things that must agree, tested against each other.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from littlecoder import judge_gate
from littlecoder.config import load_config

CORPUS_PATH = (
    Path(__file__).resolve().parents[2]
    / "scripts"
    / "checks"
    / "fixtures"
    / "judge-flag-corpus.json"
)

# Floors, so a corpus that quietly shrinks or stops discriminating fails
# instead of passing cheaply. These are the values the corpus shipped with.
MIN_CASES = 40
MIN_DAEMON_ON = 25
MIN_LEGACY_MISSES = 10


def _corpus() -> dict:
    assert CORPUS_PATH.exists(), (
        "the shared corpus is missing at %s -- this test and "
        "scripts/checks/verify-judge-flag-guard.ps1 both read it, and neither "
        "means anything without it" % CORPUS_PATH
    )
    return json.loads(CORPUS_PATH.read_text(encoding="utf-8"))


CORPUS = _corpus()
CASES = CORPUS["cases"]


def _daemon_answer(tmp_path: Path, text: str):
    """What the DAEMON sees: its own loader, on a file written byte for byte."""
    p = tmp_path / "little-coder.config.yaml"
    with open(p, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    try:
        return bool(load_config(p).observer.judge_enabled)
    except Exception as exc:  # noqa: BLE001
        return "error:" + type(exc).__name__


def test_corpus_is_large_and_discriminating():
    """A differential over a corpus that agrees trivially proves nothing."""
    assert len(CASES) >= MIN_CASES
    on = [c for c in CASES if c["daemon_expected"] is True]
    assert len(on) >= MIN_DAEMON_ON, "not enough rows actually turn the flag on"
    off = [c for c in CASES if c["daemon_expected"] is False]
    assert off, "no OFF controls -- a guard that denies everything would pass"
    assert len({c["id"] for c in CASES}) == len(CASES), "duplicate case ids"


@pytest.mark.parametrize("case", CASES, ids=[c["id"] for c in CASES])
def test_the_two_deciders_agree(tmp_path, case):
    """THE load-bearing assertion: whenever the daemon would run with the judge
    ON, the commit-time decider says ON too. A new YAML spelling that makes
    them disagree in that direction turns this RED."""
    daemon = _daemon_answer(tmp_path, case["yaml"])
    guard = judge_gate.enabled_in_yaml_text(case["yaml"])

    if daemon is True:
        assert guard.enabled, (
            "UNSAFE DISAGREEMENT on %r (%s): the daemon reads judge_enabled as "
            "ON and the commit-time decider does not see it. This is the exact "
            "defect class the gate replaced." % (case["id"], case["why"])
        )

    # Both sides are also PINNED, so a PyYAML or pydantic upgrade that changes
    # YAML boolean semantics surfaces here and a human decides, rather than
    # silently moving what the guard means.
    assert daemon == case["daemon_expected"], (
        "the daemon's own answer for %r changed: pinned %r, now %r"
        % (case["id"], case["daemon_expected"], daemon)
    )
    assert guard.enabled == case["guard_expected"], (
        "the guard's answer for %r changed: pinned %r, now %r"
        % (case["id"], case["guard_expected"], guard.enabled)
    )


def test_over_denial_is_only_ever_in_the_safe_direction():
    """The guard is deliberately a SUPERSET of the loader (every document of a
    multi-document stream, and the key at any depth). Over-denying a commit
    costs a conversation; under-denying is the bug. Assert the asymmetry holds
    for every pinned row, and that the over-denials are the four known ones."""
    unsafe = [c for c in CASES if c["daemon_expected"] is True and not c["guard_expected"]]
    assert not unsafe, [c["id"] for c in unsafe]
    over = sorted(
        c["id"] for c in CASES if c["guard_expected"] and c["daemon_expected"] is not True
    )
    assert over == [
        "inside_a_sequence",
        "multi_doc_second",
        "nested_elsewhere",
        "top_level_key",
    ], over


def test_the_replaced_regex_really_was_blind():
    """Kept executable so the reason the pattern was removed does not decay
    into a claim in a document. The regex is the one that shipped at
    check-judge-flag.ps1:114 until 2026-08-30."""
    rx = re.compile(CORPUS["legacy_regex"])
    missed = [
        c["id"]
        for c in CASES
        if c["daemon_expected"] is True and not rx.search(c["yaml"])
    ]
    assert len(missed) >= MIN_LEGACY_MISSES, missed
    # And the recorded per-case values match what the pattern actually does.
    for c in CASES:
        assert bool(rx.search(c["yaml"])) == c["legacy_regex_saw"], c["id"]
